// References:
//   NES 2.0 default expansion device field:
//     https://www.nesdev.org/wiki/NES_2.0#Default_Expansion_Device

use std::default::Default;
use std::fmt;

#[derive(Clone, Copy, Debug, Eq, PartialEq, Default)]
pub enum ExpansionDevice {
    #[default]
    Unspecified,
    StandardControllers,
    NESFourScore,
    FamicomFourPlayerAdapter,
    VsSystemVia4016,
    VsSystemVia4017,
    Reserved,
    VsZapper,
    Zapper,
    TwoZappers,
    BandaiHyperShotLightgun,
    PowerPadSideA,
    PowerPadSideB,
    FamilyTrainerSideA,
    FamilyTrainerSideB,
    ArkanoidVausControllerNES,
    ArkanoidVausControllerFamicom,
    TwoVausControllersPlusFamicomDataRecorder,
    KonamiHyperShotController,
    CoconutsPachinkoController,
    ExcitingBoxingPunchingBag,
    JissenMahjongController,
    PartyTap,
    OekaKidsTablet,
    SunsoftBarcodeBattler,
    MiraclePianoKeyboard,
    PokkunMoguraa,
    TopRider,
    DoubleFisted,
    Famicom3DSystem,
    DoremikkoKeyboard,
    ROBGyroSet,
    FamicomDataRecorder,
    ASCIITurboFile,
    IGSStorageBattleBox,
    FamilyBASICKeyboard,
    DongdaPEC586Keyboard,
    BitCorpBit79Keyboard,
    SuborKeyboard,
    SuborKeyboardMouse3x8,
    SuborKeyboardMouse24,
    SNESMouse,
    Multicart,
    TwoSNESControllers,
    RacerMateBicycle,
    UForce,
    ROBStackUp,
    CityPatrolmanLightgun,
    SharpC1CassetteInterface,
    StandardControllerSwapped,
    ExcaliborSudokuPad,
    ABLPinball,
    GoldenNuggetCasino,
}

impl From<u8> for ExpansionDevice {
    fn from(flags: u8) -> Self {
        match flags & 0b0011_1111 {
            0x01 => ExpansionDevice::StandardControllers,
            0x02 => ExpansionDevice::NESFourScore,
            0x03 => ExpansionDevice::FamicomFourPlayerAdapter,
            0x04 => ExpansionDevice::VsSystemVia4016,
            0x05 => ExpansionDevice::VsSystemVia4017,
            0x06 => ExpansionDevice::Reserved,
            0x07 => ExpansionDevice::VsZapper,
            0x08 => ExpansionDevice::Zapper,
            0x09 => ExpansionDevice::TwoZappers,
            0x0A => ExpansionDevice::BandaiHyperShotLightgun,
            0x0B => ExpansionDevice::PowerPadSideA,
            0x0C => ExpansionDevice::PowerPadSideB,
            0x0D => ExpansionDevice::FamilyTrainerSideA,
            0x0E => ExpansionDevice::FamilyTrainerSideB,
            0x0F => ExpansionDevice::ArkanoidVausControllerNES,
            0x10 => ExpansionDevice::ArkanoidVausControllerFamicom,
            0x11 => ExpansionDevice::TwoVausControllersPlusFamicomDataRecorder,
            0x12 => ExpansionDevice::KonamiHyperShotController,
            0x13 => ExpansionDevice::CoconutsPachinkoController,
            0x14 => ExpansionDevice::ExcitingBoxingPunchingBag,
            0x15 => ExpansionDevice::JissenMahjongController,
            0x16 => ExpansionDevice::PartyTap,
            0x17 => ExpansionDevice::OekaKidsTablet,
            0x18 => ExpansionDevice::SunsoftBarcodeBattler,
            0x19 => ExpansionDevice::MiraclePianoKeyboard,
            0x1A => ExpansionDevice::PokkunMoguraa,
            0x1B => ExpansionDevice::TopRider,
            0x1C => ExpansionDevice::DoubleFisted,
            0x1D => ExpansionDevice::Famicom3DSystem,
            0x1E => ExpansionDevice::DoremikkoKeyboard,
            0x1F => ExpansionDevice::ROBGyroSet,
            0x20 => ExpansionDevice::FamicomDataRecorder,
            0x21 => ExpansionDevice::ASCIITurboFile,
            0x22 => ExpansionDevice::IGSStorageBattleBox,
            0x23 => ExpansionDevice::FamilyBASICKeyboard,
            0x24 => ExpansionDevice::DongdaPEC586Keyboard,
            0x25 => ExpansionDevice::BitCorpBit79Keyboard,
            0x26 => ExpansionDevice::SuborKeyboard,
            0x27 => ExpansionDevice::SuborKeyboardMouse3x8,
            0x28 => ExpansionDevice::SuborKeyboardMouse24,
            0x29 => ExpansionDevice::SNESMouse,
            0x2A => ExpansionDevice::Multicart,
            0x2B => ExpansionDevice::TwoSNESControllers,
            0x2C => ExpansionDevice::RacerMateBicycle,
            0x2D => ExpansionDevice::UForce,
            0x2E => ExpansionDevice::ROBStackUp,
            0x2F => ExpansionDevice::CityPatrolmanLightgun,
            0x30 => ExpansionDevice::SharpC1CassetteInterface,
            0x31 => ExpansionDevice::StandardControllerSwapped,
            0x32 => ExpansionDevice::ExcaliborSudokuPad,
            0x33 => ExpansionDevice::ABLPinball,
            0x34 => ExpansionDevice::GoldenNuggetCasino,
            _ => ExpansionDevice::Unspecified,
        }
    }
}

impl fmt::Display for ExpansionDevice {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", match self {
            ExpansionDevice::Unspecified => "Unspecified",
            ExpansionDevice::StandardControllers => "Standard NES/Famicom controllers",
            ExpansionDevice::NESFourScore => "NES Four Score/Satellite with two additional standard controllers",
            ExpansionDevice::FamicomFourPlayerAdapter => "Famicom Four Players Adapter with two additional standard controllers using the \"simple\" protocol",
            ExpansionDevice::VsSystemVia4016 => "Vs. System (1P via 0x4016)",
            ExpansionDevice::VsSystemVia4017 => "Vs. System (1P via 0x4017)",
            ExpansionDevice::Reserved => "Reserved",
            ExpansionDevice::VsZapper => "Vs. Zapper",
            ExpansionDevice::Zapper => "Zapper (0x4017)",
            ExpansionDevice::TwoZappers => "Two Zappers",
            ExpansionDevice::BandaiHyperShotLightgun => "Bandai Hyper Shot Lightgun",
            ExpansionDevice::PowerPadSideA => "Power Pad Side A",
            ExpansionDevice::PowerPadSideB => "Power Pad Side B",
            ExpansionDevice::FamilyTrainerSideA => "Family Trainer Side A",
            ExpansionDevice::FamilyTrainerSideB => "Family Trainer Side B",
            ExpansionDevice::ArkanoidVausControllerNES => "Arkanoid Vaus Controller (NES)",
            ExpansionDevice::ArkanoidVausControllerFamicom => "Arkanoid Vaus Controller (Famicom)",
            ExpansionDevice::TwoVausControllersPlusFamicomDataRecorder => "Two Vaus Controllers plus Famicom Data Recorder",
            ExpansionDevice::KonamiHyperShotController => "Konami Hyper Shot Controller",
            ExpansionDevice::CoconutsPachinkoController => "Coconuts Pachinko Controller",
            ExpansionDevice::ExcitingBoxingPunchingBag => "Exciting Boxing Punching Bag (Blowup Doll)",
            ExpansionDevice::JissenMahjongController => "Jissen Mahjong Controller",
            ExpansionDevice::PartyTap  => "Party Tap  ",
            ExpansionDevice::OekaKidsTablet => "Oeka Kids Tablet",
            ExpansionDevice::SunsoftBarcodeBattler => "Sunsoft Barcode Battler",
            ExpansionDevice::MiraclePianoKeyboard => "Miracle Piano Keyboard",
            ExpansionDevice::PokkunMoguraa => "Pokkun Moguraa (Whack-a-Mole Mat and Mallet)",
            ExpansionDevice::TopRider => "Top Rider (Inflatable Bicycle)",
            ExpansionDevice::DoubleFisted => "Double-Fisted (Requires or allows use of two controllers by one player)",
            ExpansionDevice::Famicom3DSystem => "Famicom 3D System",
            ExpansionDevice::DoremikkoKeyboard => "Doremikko Keyboard",
            ExpansionDevice::ROBGyroSet => "R.O.B. Gyro Set",
            ExpansionDevice::FamicomDataRecorder => "Famicom Data Recorder (\"silent\" keyboard)",
            ExpansionDevice::ASCIITurboFile => "ASCII Turbo File",
            ExpansionDevice::IGSStorageBattleBox => "IGS Storage Battle Box",
            ExpansionDevice::FamilyBASICKeyboard => "Family BASIC Keyboard plus Famicom Data Recorder",
            ExpansionDevice::DongdaPEC586Keyboard => "Dongda PEC-586 Keyboard",
            ExpansionDevice::BitCorpBit79Keyboard => "Bit Corp. Bit-79 Keyboard",
            ExpansionDevice::SuborKeyboard => "Subor Keyboard",
            ExpansionDevice::SuborKeyboardMouse3x8 => "Subor Keyboard plus mouse (3x8-bit protocol)",
            ExpansionDevice::SuborKeyboardMouse24 => "Subor Keyboard plus mouse (24-bit protocol)",
            ExpansionDevice::SNESMouse => "SNES Mouse (0x4017.d0)",
            ExpansionDevice::Multicart => "Multicart",
            ExpansionDevice::TwoSNESControllers => "Two SNES controllers replacing the two standard NES controllers",
            ExpansionDevice::RacerMateBicycle => "RacerMate Bicycle",
            ExpansionDevice::UForce => "U-Force",
            ExpansionDevice::ROBStackUp => "R.O.B. Stack-Up",
            ExpansionDevice::CityPatrolmanLightgun => "City Patrolman Lightgun",
            ExpansionDevice::SharpC1CassetteInterface => "Sharp C1 Cassette Interface",
            ExpansionDevice::StandardControllerSwapped => "Standard Controller with swapped Left-Right/Up-Down/B-A",
            ExpansionDevice::ExcaliborSudokuPad => "Excalibor Sudoku Pad",
            ExpansionDevice::ABLPinball => "ABL Pinball",
            ExpansionDevice::GoldenNuggetCasino => "Golden Nugget Casino extra buttons",
        })
    }
}
