// References:
//   NES mapper list:
//     https://www.nesdev.org/wiki/Mapper
//     https://www.nesdev.org/wiki/NES_2.0_Mapper_List

use std::default::Default;
use std::fmt::{self};

#[derive(Clone, Copy, Debug, Eq, PartialEq, Default)]
pub enum Mapper {
    #[default]
    Unrecognized,
    Unknown {
        ines_mapper_number: u32,
    },
    MMC1,
    NROM,
    SxROM,
    UxROM,
    CNROM,
    MMC3,
    MMC5,
    AxROM,
    MMC2,
    PxROM,
    MMC4,
    ColorDreams,
    CPROM,
    ContraFunction16,
    BandaiEPROM,
    UNROM512,
    JalecoSS8806,
    Namco163,
    VRC4a,
    VRC2a,
    VRC2b,
    VRC6a,
    VRC4b,
    VRC6b,
    BNROM,
    RAMBO1,
    GxROM,
    AfterBurner,
    FME7,
    Camerica,
    VRC3,
    PirateMMC3,
    VRC1,
    Namco109,
    NINA03,
    VRC7,
    JALECOJF13,
    SenjouNoOokami,
    NESEVENT,
    NINA06,
    TxSROM,
    TQROM,
    BandaiEPROM24C01,
    SUBOR166,
    SUBOR167,
    CrazyClimber,
    CNROMWithProtection,
    PirateMMC3_4k,
    DxROM,
    Namco175,
    Action52,
    CodemastersQuattro,
    VRC4c,
    VRC4e,
    VRC4d,
    NINA001,
    MxROM,
    SuperRussianRoulette,
    Unif158B,
}

impl From<u16> for Mapper {
    fn from(v: u16) -> Self {
        match v {
            0 => Mapper::NROM,
            1 => Mapper::MMC1,
            2 => Mapper::UxROM,
            3 => Mapper::CNROM,
            4 => Mapper::MMC3,
            5 => Mapper::MMC5,
            7 => Mapper::AxROM,
            9 => Mapper::MMC2,
            10 => Mapper::MMC4,
            11 => Mapper::ColorDreams,
            13 => Mapper::CPROM,
            15 => Mapper::ContraFunction16,
            16 => Mapper::BandaiEPROM,
            18 => Mapper::JalecoSS8806,
            19 => Mapper::Namco163,
            21 => Mapper::VRC4a,
            22 => Mapper::VRC2a,
            23 => Mapper::VRC2b,
            24 => Mapper::VRC6a,
            25 => Mapper::VRC4b,
            26 => Mapper::VRC6b,
            30 => Mapper::UNROM512,
            34 => Mapper::BNROM,
            64 => Mapper::RAMBO1,
            66 => Mapper::GxROM,
            68 => Mapper::AfterBurner,
            69 => Mapper::FME7,
            71 => Mapper::Camerica,
            73 => Mapper::VRC3,
            74 => Mapper::PirateMMC3,
            75 => Mapper::VRC1,
            76 => Mapper::Namco109,
            79 => Mapper::NINA03,
            85 => Mapper::VRC7,
            86 => Mapper::JALECOJF13,
            94 => Mapper::SenjouNoOokami,
            105 => Mapper::NESEVENT,
            113 => Mapper::NINA06,
            118 => Mapper::TxSROM,
            119 => Mapper::TQROM,
            159 => Mapper::BandaiEPROM24C01,
            166 => Mapper::SUBOR166,
            167 => Mapper::SUBOR167,
            180 => Mapper::CrazyClimber,
            185 => Mapper::CNROMWithProtection,
            192 => Mapper::PirateMMC3_4k,
            206 => Mapper::DxROM,
            210 => Mapper::Namco175,
            228 => Mapper::Action52,
            232 => Mapper::CodemastersQuattro,
            413 => Mapper::SuperRussianRoulette,
            258 => Mapper::Unif158B,
            _ => Mapper::Unknown {
                ines_mapper_number: v.into(),
            },
        }
    }
}

impl fmt::Display for Mapper {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        if let Mapper::Unknown { ines_mapper_number } = self {
            write!(f, "Unrecognized mapper {}", ines_mapper_number)
        } else {
            write!(
                f,
                "{}",
                match self {
                    Mapper::Unknown { .. } => unreachable!(),
                    Mapper::Action52 => "Action 52",
                    Mapper::AfterBurner => "After Burner ROM-based nametables",
                    Mapper::AxROM => "AxROM",
                    Mapper::BandaiEPROM24C01 => "Bandai EPROM (24C01)  ",
                    Mapper::BandaiEPROM => "Bandai EPROM (24C02)",
                    Mapper::BNROM | Mapper::NINA001 => "BNROM, NINA-001  ",
                    Mapper::Camerica => "Camerica/Codemasters (Similar to UNROM)",
                    Mapper::CNROM => "CNROM",
                    Mapper::CNROMWithProtection => "CNROM with protection diodes",
                    Mapper::CodemastersQuattro => "Camerica/Codemasters Quattro",
                    Mapper::ColorDreams => "Color Dreams",
                    Mapper::ContraFunction16 => "100-in-1 Contra Function 16",
                    Mapper::CPROM => "CPROM",
                    Mapper::CrazyClimber => "Crazy Climber",
                    Mapper::DxROM =>
                        "DxROM, Namco 118 / MIMIC-1  Simplified MMC3 predecessor lacking some features",
                    Mapper::FME7 => "FME-7, Sunsoft 5B  The 5B is the FME-7 with expansion sound",
                    Mapper::GxROM | Mapper::MxROM => "GxROM, MxROM",
                    Mapper::JALECOJF13 => "JALECO-JF-13  ",
                    Mapper::JalecoSS8806 => "Jaleco SS8806",
                    Mapper::MMC1 => "MMC1",
                    Mapper::MMC2 => "MMC2",
                    Mapper::MMC3 => "MMC3",
                    Mapper::MMC4 => "MMC4",
                    Mapper::MMC5 => "MMC5",
                    Mapper::Namco109 => "Namco 109 variant",
                    Mapper::Namco163 => "Namco 163  Contains expansion sound",
                    Mapper::Namco175 => "Namco 175 and 340  Namco 163 with different mirroring",
                    Mapper::NESEVENT => "NES-EVENT  Similar to MMC1",
                    Mapper::NINA03 => "NINA-03/NINA-06",
                    Mapper::NINA06 =>
                        "NINA-03/NINA-06??  For multicarts including mapper 79 games.",
                    Mapper::NROM => "NROM",
                    Mapper::PirateMMC3 => "Pirate MMC3 derivative",
                    Mapper::PirateMMC3_4k => "Pirate MMC3 derivative",
                    Mapper::PxROM => "PxROM",
                    Mapper::RAMBO1 => "RAMBO-1 (MMC3 clone with extra features)",
                    Mapper::SenjouNoOokami => "Senjou no Ookami",
                    Mapper::SUBOR166 => "SUBOR",
                    Mapper::SUBOR167 => "SUBOR",
                    Mapper::SuperRussianRoulette => "Super Russian Roulette",
                    Mapper::SxROM => "SxROM",
                    Mapper::TQROM => "TQROM, MMC3  Has both CHR ROM and CHR RAM",
                    Mapper::TxSROM => "TxSROM, MMC3  MMC3 with independent mirroring control",
                    Mapper::Unif158B => "UNIF MAPR 158B (iNES 258)",
                    Mapper::Unrecognized => "Unrecognized",
                    Mapper::UNROM512 => "UNROM 512",
                    Mapper::UxROM => "UxROM",
                    Mapper::VRC1 => "VRC1",
                    Mapper::VRC2a => "VRC2a",
                    Mapper::VRC2b | Mapper::VRC4e => "VRC2b, VRC4e",
                    Mapper::VRC3 => "VRC3",
                    Mapper::VRC4a | Mapper::VRC4c => "VRC4a, VRC4c",
                    Mapper::VRC4b | Mapper::VRC4d => "VRC4b, VRC4d",
                    Mapper::VRC6a => "VRC6a  Contains expansion sound",
                    Mapper::VRC6b => "VRC6b  Contains expansion sound",
                    Mapper::VRC7 => "VRC7 Contains expansion sound",
                }
            )
        }
    }
}
