// References:
//   Pan Docs (CC0) — pre-DSi-era subset:
//     https://gbdev.io/pandocs/The_Cartridge_Header.html#0144-0145---new-licensee-code
//
// Maker (licensee) codes are 2-character uppercase ASCII identifiers assigned
// by Nintendo to publishers and developers. The same registry is shared
// across Game Boy / Game Boy Color / GBA / DS / DSi / 3DS, but several codes
// were reassigned between the GB and DS eras (e.g. `01` was historically
// labeled "Nintendo R&D1" for GB titles and is plain "Nintendo" on DS).
// This table reflects DS-era usage and is intentionally separate from
// `gameboy::lookup_new_licensee` so the GB/GBA output isn't disturbed.

pub fn lookup_nds_licensee(code: &[u8; 2]) -> Option<&'static str> {
    match code {
        b"00" => Some("None"),
        b"01" => Some("Nintendo"),
        b"02" => Some("Rocket Games"),
        b"08" => Some("Capcom"),
        b"09" => Some("Hot-B"),
        b"0A" => Some("Jaleco"),
        b"0B" => Some("Coconuts Japan"),
        b"0H" => Some("Starfish"),
        b"0P" => Some("Game Village"),
        b"13" => Some("Electronic Arts Japan"),
        b"18" => Some("Hudson Soft"),
        b"1A" => Some("Yanoman"),
        b"1C" => Some("Tecmo"),
        b"1F" => Some("Virgin Games"),
        b"1P" => Some("Creatures Inc."),
        b"1Q" => Some("TDK Core"),
        b"20" => Some("KSS"),
        b"22" => Some("Planning Office WADA"),
        b"25" => Some("San-X"),
        b"28" => Some("Kemco Japan"),
        b"29" => Some("SETA"),
        b"2H" => Some("Ubisoft Japan"),
        b"2K" => Some("NEC InterChannel"),
        b"2N" => Some("Smilesoft"),
        b"30" => Some("Viacom"),
        b"31" => Some("Carrozzeria"),
        b"32" => Some("Bandai"),
        b"34" => Some("Konami"),
        b"36" => Some("Codemasters"),
        b"37" => Some("Taito"),
        b"39" => Some("Banpresto"),
        b"41" => Some("Ubisoft"),
        b"42" => Some("Atlus"),
        b"46" => Some("System 3"),
        b"47" => Some("Spectrum HoloByte"),
        b"49" => Some("Irem"),
        b"4F" => Some("Eidos"),
        b"4Q" => Some("Disney Interactive"),
        b"4S" => Some("Black Pearl"),
        b"4X" => Some("GT Interactive"),
        b"4Y" => Some("Rare"),
        b"4Z" => Some("Crave Entertainment"),
        b"50" => Some("Absolute Entertainment"),
        b"51" => Some("Acclaim"),
        b"52" => Some("Activision"),
        b"54" => Some("Take-Two Interactive"),
        b"55" => Some("Hi Tech Expressions"),
        b"56" => Some("LJN"),
        b"58" => Some("Mattel"),
        b"5D" => Some("Midway"),
        b"5G" => Some("Majesco"),
        b"5H" => Some("3DO"),
        b"5K" => Some("Hasbro"),
        b"5L" => Some("NewKidCo"),
        b"5N" => Some("Metro3D"),
        b"5Q" => Some("LEGO Media"),
        b"5T" => Some("Cryo Interactive"),
        b"5W" => Some("Red Storm Entertainment"),
        b"5Z" => Some("Conspiracy Entertainment"),
        b"60" => Some("Titus Interactive"),
        b"61" => Some("Virgin Interactive"),
        b"64" => Some("LucasArts"),
        b"67" => Some("Ocean Software"),
        b"69" => Some("Electronic Arts"),
        b"6E" => Some("Elite Systems"),
        b"6F" => Some("Electro Brain"),
        b"6G" => Some("The Learning Company"),
        b"6L" => Some("BAM! Entertainment"),
        b"6M" => Some("Studio 3"),
        b"6S" => Some("TDK Mediactive"),
        b"6V" => Some("JoWooD"),
        b"6W" => Some("Sega"),
        b"70" => Some("Infogrames"),
        b"71" => Some("Interplay"),
        b"72" => Some("JVC"),
        b"73" => Some("Parker Brothers"),
        b"75" => Some("SCi"),
        b"78" => Some("THQ"),
        b"79" => Some("Accolade"),
        b"7D" => Some("Sierra"),
        b"7F" => Some("Kemco"),
        b"7G" => Some("Rage Software"),
        b"7J" => Some("Zoo Digital"),
        b"7L" => Some("Simon & Schuster"),
        b"7M" => Some("Asmik Ace"),
        b"7N" => Some("Empire Interactive"),
        b"7T" => Some("Scholastic"),
        b"7U" => Some("Ignition Entertainment"),
        b"80" => Some("Misawa Entertainment"),
        b"81" => Some("Teichiku"),
        b"82" => Some("Namco"),
        b"83" => Some("LOZC"),
        b"84" => Some("Koei"),
        b"86" => Some("Tokuma Shoten"),
        b"87" => Some("Tsukuda Original"),
        b"8B" => Some("Bullet-Proof Software"),
        b"8C" => Some("Vic Tokai"),
        b"8F" => Some("I'Max"),
        b"8N" => Some("Success"),
        b"8P" => Some("Sega"),
        b"90" => Some("Takara Amusement"),
        b"91" => Some("Chunsoft"),
        b"92" => Some("Video System"),
        b"93" => Some("BEC"),
        b"96" => Some("Yonezawa / S'Pal"),
        b"97" => Some("Kaneko"),
        b"99" => Some("Victor Interactive Software"),
        b"9A" => Some("Nichibutsu"),
        b"9B" => Some("Tecmo"),
        b"9H" => Some("Bottom Up"),
        b"9L" => Some("Hasbro Japan"),
        b"9N" => Some("Marvelous Entertainment"),
        b"A0" => Some("Telenet"),
        b"A1" => Some("Hori"),
        b"A4" => Some("Konami"),
        b"A7" => Some("Takara"),
        b"A9" => Some("Technos Japan"),
        b"AA" => Some("JVC"),
        b"AC" => Some("Toei Animation"),
        b"AD" => Some("Toho"),
        b"AF" => Some("Namco"),
        b"AG" => Some("Media Rings"),
        b"AH" => Some("J-Wing"),
        b"AJ" => Some("Pioneer LDC"),
        b"AK" => Some("KID"),
        b"AL" => Some("Media Factory"),
        b"AP" => Some("Infogrames Hudson"),
        b"AQ" => Some("Kiratto Ludic"),
        b"B0" => Some("Acclaim Japan"),
        b"B1" => Some("ASCII / Nexoft"),
        b"B2" => Some("Bandai"),
        b"B4" => Some("Enix"),
        b"B6" => Some("HAL Laboratory"),
        b"B7" => Some("SNK"),
        b"B9" => Some("Pony Canyon"),
        b"BA" => Some("Culture Brain"),
        b"BB" => Some("Sunsoft"),
        b"BD" => Some("Sony Imagesoft"),
        b"BF" => Some("Sammy"),
        b"BJ" => Some("Compile"),
        b"BL" => Some("MTO"),
        b"BN" => Some("Sunrise Interactive"),
        b"BP" => Some("Global A Entertainment"),
        b"C0" => Some("Taito"),
        b"C2" => Some("Kemco"),
        b"C3" => Some("Squaresoft"),
        b"C4" => Some("Tokuma Shoten"),
        b"C5" => Some("Data East"),
        b"C6" => Some("Tonkin House"),
        b"C8" => Some("Koei"),
        b"CA" => Some("Konami / Palcom"),
        b"CB" => Some("NTVIC / VAP"),
        b"CD" => Some("Meldac"),
        b"CE" => Some("Pony Canyon"),
        b"CF" => Some("Angel / Sotsu Agency"),
        b"CM" => Some("Konami CE Osaka"),
        b"CP" => Some("Enterbrain"),
        b"D1" => Some("Sofel"),
        b"D2" => Some("Quest"),
        b"D4" => Some("Ask Kodansha"),
        b"D6" => Some("Naxat Soft"),
        b"D7" => Some("Copya System"),
        b"D8" => Some("Capcom"),
        b"D9" => Some("Banpresto"),
        b"DA" => Some("Tomy"),
        b"DB" => Some("LJN Japan"),
        b"DD" => Some("NCS"),
        b"DE" => Some("Human Entertainment"),
        b"DF" => Some("Altron"),
        b"DG" => Some("Jaleco"),
        b"DK" => Some("Kodansha"),
        b"DN" => Some("Elf"),
        b"E0" => Some("Jaleco"),
        b"E2" => Some("Yutaka"),
        b"E3" => Some("Varie"),
        b"E5" => Some("Epoch"),
        b"E7" => Some("Athena"),
        b"E8" => Some("Asmik"),
        b"E9" => Some("Natsume"),
        b"EA" => Some("King Records"),
        b"EB" => Some("Atlus"),
        b"EC" => Some("Epic / Sony Records"),
        b"EL" => Some("Spike"),
        b"EM" => Some("Konami CE Tokyo"),
        b"EN" => Some("AlphaDream"),
        b"F0" => Some("A Wave"),
        b"F2" => Some("Left Field Entertainment"),
        b"FB" => Some("Psygnosis"),
        b"G1" => Some("PCCW Japan"),
        b"G4" => Some("KiKi"),
        b"G5" => Some("Open Sesame"),
        b"G6" => Some("Sims"),
        b"G7" => Some("Broccoli"),
        b"G8" => Some("Avex"),
        b"G9" => Some("D3 Publisher"),
        b"GB" => Some("Konami CE Japan"),
        b"GD" => Some("Square Enix"),
        b"IH" => Some("Yojigen"),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn resolves_known_codes() {
        assert_eq!(lookup_nds_licensee(b"01"), Some("Nintendo"));
        assert_eq!(lookup_nds_licensee(b"8P"), Some("Sega"));
        assert_eq!(lookup_nds_licensee(b"GD"), Some("Square Enix"));
        assert_eq!(lookup_nds_licensee(b"A4"), Some("Konami"));
        assert_eq!(lookup_nds_licensee(b"EB"), Some("Atlus"));
    }

    #[test]
    fn returns_none_for_unknown_codes() {
        assert_eq!(lookup_nds_licensee(b"ZZ"), None);
        assert_eq!(lookup_nds_licensee(b"\xff\xff"), None);
        assert_eq!(lookup_nds_licensee(b"  "), None);
    }
}
